language: node_js
node_js:
- '6.9.1'
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
- npm install -g codeclimate-test-reporter
before_script:
- npm rebuild node-sass
- gulp generate-index-icons
- gulp preprocess
- gulp dist-css
script:
- |
  if [ "$TEST_TYPE" = build ]; then
    npm test
  else
    if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then gulp $TEST_TYPE; fi
  fi
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
    gulp coveralls
    codeclimate-test-reporter < coverage/lcov.info
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      git config credential.helper "store --file=.git/credentials"
      echo "https://${GH_TOKEN}:@github.com" > .git/credentials
      git config --global user.name "Grommet Community Bot"
      git config --global user.email "asouza@hp.com"
      gulp dist
      gulp release:stable
    fi
  fi
env:
  matrix:
  - TEST_TYPE=build
notifications:
  slack:
    secure: KO4NG+slaqtFbK5T2FpkR8vgUPfZA5nf+oGDhOCFQXwfcEje/auWKdbSEzCMJ8RMl039wYjtz5iyN6bumD5FYuZFXAddeRiCtaIVqr/r6A536ldneQFTiieyeOYKJkh42hahjstcAKCv0mWr1GZGFc2cyNaoSZvE8/LNcOZy3Rne3ZPAgNMVKF3xkYFUzQOQLJsMEq7sW8LX+Z9zO+OAGjV3uEbiEYlS+N/0VW+ziz+TL+/gNf0rvzAjRd5v/VRudNxuVqx/frpYJzxGS6EHy1vVWFo6NomqBXHQvaEY+W+oorND6Jg0VNhJLCXOk2xxx0JZul2GurkQGex9b3UoARLTWarwOC9Vm/IhZ9Tc57H0U8B7Qxyb0KFacXJPeMqb2tPgNC0/wSIX8uLqlyUJnPqiRgII3W2V1YG3bWJssHNqg5F8WbD+kIphr4ghrW//8EZvcgVK/QS/yIXGLqKYygOYajXoHeb+dR0eCvE2b1wGG/EoZlZcaH2q9lE+1hmyli7MAW3aCmpCEoDUFPq5a8fcdDnYiGV5s1TPbPGvOsd2kYmeFnh71po+GgO07c+1QPLAXiW0YO8hzENi6HMcAdqcKMFXFWYD0fMNPSES/HwIFlAW/c1UBdh7KYCpZ4zljLrHyj1CAM8jXWJ7MTbJYsYHFNHA4eWNZotNLYvQgvs=
matrix:
  fast_finish: true
